"""Add remaining tables

Revision ID: 0308ff83ab7d
Revises: b99894ef6a0f
Create Date: 2025-12-03 20:59:26.793833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0308ff83ab7d'
down_revision: Union[str, None] = 'b99894ef6a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
