"""Initial Phase 1 migration

Revision ID: b99894ef6a0f
Revises: 
Create Date: 2025-12-03 20:58:33.444639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99894ef6a0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('country_of_residence', sa.String(length=100), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('source_of_funds', sa.Enum('EMPLOYMENT', 'BUSINESS', 'INVESTMENTS', 'INHERITANCE', 'OTHER', name='sourceoffunds'), nullable=False),
    sa.Column('monthly_income_range', sa.Enum('RANGE_0_1000', 'RANGE_1001_5000', 'RANGE_5001_10000', 'RANGE_10001_20000', 'RANGE_20000_PLUS', name='monthlyincomerange'), nullable=False),
    sa.Column('tax_identification_number', sa.String(length=50), nullable=True),
    sa.Column('kyc_status', sa.Enum('PENDING', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='kycstatus'), nullable=False),
    sa.Column('kyc_rejection_reason', sa.Text(), nullable=True),
    sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kyc_reviewer_id', sa.Integer(), nullable=True),
    sa.Column('account_status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'CLOSED', name='accountstatus'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_method', sa.Enum('NONE', 'SMS', 'AUTHENTICATOR', name='twofactormethod'), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('account_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_terms', sa.Boolean(), nullable=False),
    sa.Column('accepted_privacy_policy', sa.Boolean(), nullable=False),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=12), nullable=False),
    sa.Column('routing_number', sa.String(length=9), nullable=True),
    sa.Column('swift_code', sa.String(length=11), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('account_type', sa.Enum('CHECKING', 'SAVINGS', 'BUSINESS', name='accounttype'), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', name='currency'), nullable=False),
    sa.Column('account_tier', sa.Enum('BASIC', 'PREMIUM', 'ENTERPRISE', name='accounttier'), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ledger_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('overdraft_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('overdraft_enabled', sa.Boolean(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('minimum_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('daily_transaction_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('daily_withdrawal_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monthly_transaction_limit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('check_writing_enabled', sa.Boolean(), nullable=False),
    sa.Column('wire_transfer_enabled', sa.Boolean(), nullable=False),
    sa.Column('ach_transfer_enabled', sa.Boolean(), nullable=False),
    sa.Column('international_transfer_enabled', sa.Boolean(), nullable=False),
    sa.Column('direct_deposit_enabled', sa.Boolean(), nullable=False),
    sa.Column('bill_pay_enabled', sa.Boolean(), nullable=False),
    sa.Column('debit_card_enabled', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'INACTIVE', 'FROZEN', 'CLOSED', name='accountstatusenum'), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('closure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
